outputs_path: new_outputs
results_path: results
plots_path: results/rq_plots
domain_plots_path: results/domain_plots

experiment:
  runs_to_average: 3

domains:
  - os
  - db
  - ws
  - alf